.github/workflows/cloudformation-lint.yaml

Run `cfn-lint`[[1]] on all `template.yaml` files in the `infrastructure`
folder when a pull request is opened, re-opened or updated.
This isn't the most useful now, but it will be more useful once we start 
properly working on the prototype.
[1]: https://github.com/aws-cloudformation/cfn-lint

Run CloudFormation linter on pull request

---

infrastructure/README.md
infrastructure/fargate-demo/README.md

Our AWS account is now in `gds-cli` so we can remove the complicated
`aws-vault` commands.
We now have multiple stacks and the instructions apply to all of them.

Update instructions to get AWS credentials

---

infrastructure/kubernetes-demo/README.md
infrastructure/kubernetes-demo/hello-world.yaml
infrastructure/kubernetes-demo/template.yaml

This PR creates a DocumentDB backing service in CloudFormation, stores the username and password as secrets in AWS Secrets Manager, grants the Hello World pods access to read that secret and passes the database details to the pods as environment variables.
This is preparatory work before modifying the Node app to connect to the database and read / write data to it. 
Each commit has more details on the individual changes.
---
[Trello](https://trello.com/c/COBq3ILM/1362-create-a-mongodb-backing-service-that-speaks-to-the-eks-cluster)

Create a DocumentDB backing service and pass credentials to the pods

---

infrastructure/common/template.yaml

[GUA-137](https://govukverify.atlassian.net/browse/GUA-137)
Configures the cluste to add our required DNS for the Enterprise Solid Server.

GUA-137 - Add DNS route and nameservers to cloudformation

---

infrastructure/fargate-demo/template.yaml

Use the delegated DNS added in [[1]] to create a DNS record, certificate
and load balancer rules to serve the fargate demo service on a
subdomain over HTTPS.
It's now available on https://fargate-demo.solid.integration.account.gov.uk/
This follows the example at [[2]] to redirect HTTP traffic to the same
URL on HTTPS.
Also remove the load balancer DNS name from the outputs since the
service is now available at a human-friendly URL.
[1]: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-listener-redirectconfig.html
[2]: https://github.com/alphagov/di-solid-prototype/pull/9
---
[JIRA](https://govukverify.atlassian.net/jira/software/c/projects/GUA/boards/195?modal=detail&selectedIssue=GUA-137)

Use a domain for the fargate demo service 

---

README.md
infrastructure/prototype-app/build_and_push_image.sh
infrastructure/prototype-app/deploy.sh
infrastructure/prototype-app/samconfig.toml
infrastructure/prototype-app/template.yaml

We're not at CD yet, but this PR sets up everything we need to deploy the prototype app to https://prototype.solid.integration.account.gov.uk/ on ECS / Fargate. 
It borrows heavily from the CloudFormation we wrote before to deploy the demo Node app to Fargate.
`deploy.sh` in `infrastructure/prototype-app` does everything we need our CD tool to do, so hopefully it'll be fairly easy to  move over to a Github action in the near future.
Note that this specifies to deploy only one container. Initially we'll be using in-memory session management, so having multiple deployed containers brings the risk of requests being split between containers which will break as only one will have the session state.
I *think* it's possible to get the load balancer to do session-aware routing, but until we've …

GUA-220: Deploy the prototype app

---

.github/dependabot.yml

This is an odd one, when we update the main branch, it appears
dependabot is not automatically rebasing branches. I'm used to this
happening automatically.
[github says][1] these should happen automatically, and I'm assuming
that it's finding main ok as the [target-branch][2]. So lets try setting
this expicitly and see if that overrides any weirdness going on
[1]: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#rebase-strategy
[2]: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#target-branch

Explicitly set Rebase auto as debpendabot strategy

---

README.md

This installs exactly what's in `package-lock.json` so developers
always have the same versions of everything when working on this app.
The CI workflow already used `npm ci` so doesn't need updating.

BAU: Use `npm ci` to install dependencies

---

package.json
src/app.ts

Setting `--max-warnings=0` means that ESLint will error and raise an exit code 1 if there are any warnings found, which means that `npm run test` will fail.
Github has started showing these warnings in PR summaries, so this change will help us catch them earlier.
I recommend installing the [ESLint VSCode plugin](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) which will highlight warnings and offer solutions in VSCode.
---
This does mean we have to put in a bit of extra effort to make sure our code is 'clean and tidy', but I think
1. It's not going to be a lot more effort
2. We should be working to best practices, even on a prototype project
It's open for discussion though - I think disabling warnings is quite an opinionated setting for our tooling.

GUA-220: Forbid linter warnings

---

.github/workflows/build_and_deploy.yaml
infrastructure/prototype-app/template.yaml

Three quick changes:
- Extend conditionality to the create oidc provider (following github docs)
- Tiny refactor to put amazon region at the top
- add aud to trust policy
- Finally it seems we couldn't find the secret because we weren't telling the job to run in the right env.
These have been SAM deployed and checked within AWS.

Gua 220 fixes to ci

---

.github/workflows/build_and_deploy.yaml

In the [Github guide](https://docs.github.com/en/actions/deployment/deploying-to-your-cloud-provider/deploying-to-amazon-elastic-container-service) these had what looks like commit SHAs on the end.
I figured we just wanted something less specific, seems from the [amazon-ecs-render-task-definition](https://github.com/aws-actions/amazon-ecs-render-task-definition) page, these need `@v1` on the end

Add @v1 to ecs-deploy-task-action

---

.github/workflows/build_and_deploy.yaml

Previous attempts seemed to hit a brick wall. We wanted a task
definition to follow along with that github's guides wanted. They
suggsted that should be introduced as-code defined somewhere like
.aws/task-definition.json.
However we've defined ours in cloud formation, and I can't see a way to
supply it with the version that exists in AWS, and get it to pull JSON.
Looking at Alex's working deploy.sh though, we can perhaps skip all
that.
All we want to do is:
1. build a docker image (working!)
2. push it to ECR (working!)
3. sam deploy
I think this is what the new element in this commit should help with

Try using aws-actions/aws-cloudformation-github-deploy

---

infrastructure/prototype-app/template.yaml
package-lock.json
package.json
src/app.ts
src/config.ts
src/controllers/login.ts
src/routes/login.ts
src/views/login/start.njk
src/views/login/success.njk

This PR sets up the basics we need to do a login with Inrupt's `start.inrupt.com` ESS deployment while we're putting the finishing touches on ours. 
It's mostly following [Inrupt's tutorial](https://docs.inrupt.com/developer-tools/javascript/client-libraries/tutorial/authenticate-nodejs-web-server/) with one notable change (see the commit message on 53cd10cd43f7201dee9bc879d93beb8e60378501 for details).
It also sets up client side session management via `cookie-session`. I thought about trying to go rogue from the tutorial and use `express-session` for in-memory server side sessions, but actually I think we get some benefits from putting the whole session in a cookie (see the commit message on 40d0d468d0eb2e12c80e7bdbcdc8b8dacd7d77dc). There's one noticeable downside which is that cookies …

GUA-230: Add login via start.inrupt.com 

---

src/controllers/info.ts
src/test/info.test.ts

It needs to be `http` - we missed this in #55

GUA-205: Fix local redirect URI

---

src/config.ts
src/controllers/login.ts
src/test/config.test.ts

Now we have a client ID document for this app (see #55) we can use it and the information it contains while logging in, instead of providing a client name etc. directly. 
This also means we can add this client ID to the allowlist in ESS, which will permit this app to create WebID profiles and pods on behalf of users.
I've also cherry-picked in 4c8f1483e5eb14680000e20ed081b391a5f6395b from #54 because I got bored of typing the domain out each time.

GUA-205: Use client ID on login 

---

src/controllers/login.ts
src/lib/pod.ts

Following the documentation at:
https://docs.inrupt.com/ess/latest/services/service-webid/#create-a-profile-document
https://docs.inrupt.com/ess/latest/services/service-pod-management/#provision-create-pod
https://docs.inrupt.com/ess/latest/services/service-webid/#add-pod-location-to-profile-document
If a user's WebID returns a 404 it means we've not created a profile
for them yet, so go through the process of:
1. Create a WebID profile
2. Create a pod
3. Add a link to that pod to the WebID profile

GUA-205: Create a pod and WebID profile when a user first logs in

---

src/app.ts
src/controllers/identity/save.ts
src/routes/identity.ts
src/views/identity/save.njk

This isn't exactly a coherent feature yet.
But my hope is this sketches out enough of where the rest of the [Identity screens](https://www.figma.com/file/f6Kn3ZhjCiiJSIQpNFt7On/Solid-example-flows?node-id=966%3A1186) can go, so those can start filling in.
Next up, still a part of GUA 209, well try and write a fixture to the pod on a post to the /identity/save path.

GUA 209: save identity

---

src/app.ts

There is a dependency on static assets from `govuk-frontend` (aka the
Design System), such as fonts. Static asset requests were returning 404s.
This updates the code so that express can get those static files from
the relevant location under `node_modules`.

Fix `govuk-frontend` assets 404-ing on local

---

src/app.ts
src/controllers/account.ts
src/controllers/identity/save.ts
src/locales/cy/translation.json
src/locales/en/translation.json
src/public/stylesheets/application.scss
src/routes/account.ts
src/views/account/activity.njk
src/views/account/delete-proof-of-identity.njk
src/views/account/home.njk
src/views/account/settings.njk
src/views/account/your-proof-of-identity.njk
src/views/index.njk
src/views/layouts/account.njk
src/views/layouts/base.njk

Build static frontend templates and views of the account dashboard and
account subpages as illustrated in the [Figma prototype](https://www.figma.com/file/f6Kn3ZhjCiiJSIQpNFt7On/Solid-example-flows?node-id=966%3A2514).
These views are the basis for the user's dashboard where they can
view their data. Currently the data is hard coded, but the intention is
that the dashboard will interact with the user's solid pod and display
their identity attributes, communication preferences and existing access
grants.

GUA-210: static views for account home & subpages

---

src/controllers/identity/ipv.ts
src/controllers/login.ts
src/lib/pod.ts
src/routes/identity.ts

When a user first starts the IPV journey, check their pod for any
previously stored credentials. If both the credentials are there, take
them past the questions to the re-use page.
Note: We're not doing any validation of these credentials, or even
checking the binary JWTs are present - we're only looking to see that
there's resources at the metadata paths where we're expecting them to
be. This is a deliberate choice made to speed up the development of
this PoC; in the real thing we'd need to fetch the JWTs, decode them
and run validity checks or re-use the data for other CRIs.
The 'use saved identity' page doesn't lead on to the rest 
of the journey yet, there's still some connecting that needs doing.

GUA-247: Check pod for previously saved credentials

---

package.json

This will prevent issues with running the dev server after a PR has
been merged that adds new packages.

BAU: Add `npm ci` to build step

---

src/controllers/login.ts

This was causing the app to crash when a user spent more than 3.5
seconds logging into their account as that's the default request
timeout length in Express.
Changing the login function to not `await` for the response from
`session.login` closes the request once the user's been redirected to
the IDp. This has no impact on how the login works or what the user
sees.
This is the only part of the `loginGet` function that's async so we can
also make the whole function synchronous now.

BAU: Close login request once user is sent to IDp

---

src/controllers/account.ts
src/locales/cy/translation.json
src/locales/en/translation.json
src/routes/account.ts
src/views/account/your-proof-of-identity.njk

- Place the Account area behind login
- Put a check into the "your prooved identity" area and conditionally render two templates
1. With some hard coded content simulating the two saved checks
2. With a page noting the user has no saved content and offering them the start of the joureny (NB not in designs!)
- Happy path links to delete button, which redirects back to "your prooved identity" after clearing the pod
An extension of this would be to populate the table dynamically from pod linked data.
This would involve adding an updated at item of RDF, and a localised string describing what the check is.
This can be a follow up "nice to have" PR as the delete portion is the key thing to demo here.

GUA 231 account home area

---

.eslintrc.json
src/controllers/dbs.ts
src/controllers/identity/complete.ts
src/controllers/identity/ipv.ts
src/lib/middleware/redirectIfNotLoggedIn.ts
src/locales/cy/translation.json
src/locales/en/translation.json
src/views/dbs/apply-for-a-basic-dbs-check.njk
src/views/dbs/prove-your-identity.njk
src/views/dbs/request-a-basic-dbs-check.njk
src/views/identity/complete/identity-confirmed.njk
src/views/identity/complete/saved.njk

This PR connects the end of the IPV journey to the beginning of the service journey that the user started from. 
When a service mock passes the user to login and IPV, it writes the service name and the URL of the next page in the service journey to the user's session. Once the user reaches the end of the IPV journey, either by answering all the questions or re-using stored checks, it reads these values back out the user's session, populates the relevant parts in the page template with the service name and sends the user back to the right place.
I've not yet set up the routing between the rest of the pages in the DBS journey, so only the first two work for now.
I got into a bit of a git mess when rebasing this onto the prettier changes, so it'd be good if the reviewer could run this branch …

GUA-231: Connect end of IPV journey to start of service journey

---

src/controllers/dbs.ts
src/routes/dbs.ts
src/views/dbs/check-your-details.njk
src/views/dbs/mobile-number.njk
src/views/dbs/other-names.njk

Allow a user to click through the pages in the DBS journey after they've proved their identity.
I wasn't completely sure where this journey should end - we have a check your details page, review your application and a disclaimer but I couldn't see a confirmation page to put after that. I've probably missed something.
I've also not populated the 'review your application' page - some of the details there need to come from the IPV journey so I'd need to implement decoding the stored checks if someone is reusing a stored identity.  We can add that functionality in a later PR if it's required.

GUA-231: Join up end of DBS journey

---

src/controllers/identity/ipv.ts
src/controllers/login.ts
src/routes/login.ts
src/views/index.njk

This PR adds two small fixes / improvements to the app session in the PoC: 
1. Add a button on the homepage that sends the user to a route which clears their local app session and redirects them back to the homepage.
2. Update the KBV question state machine to clear any previous answers when a user gets to the KBV intro page.
These will make it easier to demo the PoC app

BAU: Session fixes

---

package.json

Government Frontend is currently supporting LibreSass and Ruby Sass
alongside Dart Sass. math.div is not available in either. So the
deprcation warning / preference does not have a clear mitigation path
until the design system is able to remove these conflicting support
requriements (aimed at October 2022, or so I hear).
Source: https://github.com/alphagov/govuk-frontend/issues/2238
In the meantime, we get a ton of noise everytime we spin up an app.
Theoretically Dart Sass (which we're using here) can silence these
errors since v1.34.0:
https://github.com/sass/dart-sass/releases/tag/1.34.0
Other folks who have encountered this have even left handy PRs we can
:eye:
https://github.com/DanCorderSoftwire/govuk-design-system-dotnet/commit/eb12d7553b865b5e7f5c4d6f428b5b7e230a54a6#diff-7bca01eb70 …

BAU: Supress SASS warnings

---

Dockerfile

We did this in the NVMrc and I forgot about the docker image
So prod was still on v18.x

BAU: Downgrade docker image to node v16.16.0

---

src/controllers/account.ts

I spotted using podbrowser that we we were only deleting the `metadata`
files not the `check` jwt blobs

Fix: Delete Blobs as well as RDF Metadata

---

src/views/dbs/layout.njk

Previously the service name at on the DBS pages was 'Personal tax
account' which was a bit confusing.
**Before:** 
**After:**

BAU: Fix title in DBS journey

---

src/app.ts
src/controllers/nino.ts
src/lib/credentials.ts
src/lib/nationalInsurance.ts
src/locales/cy/translation.json
src/locales/en/translation.json
src/routes/nino.ts
src/views/nino/enter-your-number.njk
src/views/nino/layout.njk
src/views/nino/weve-verified-your-number.njk
src/views/nino/youve-saved-your-number.njk

Set up everything needed for the fake 'National Insurance number checker' service that asks a user for their National Insurance number after they've proved their identity, and saves a credential containing it back to the user's pod.
This doesn't implement the separate client ID we're expecting to need for these pages to behave like a separate service, that'll come in a later PR.
I've taken a bit of liberty here in defining the NI number as a property that's defined in a DWP-owned vocab, but it demonstrates the spirit of cross-government collaboration.

GUA-314: Set up the 'National Insurance number checker' service

---

package-lock.json
package.json
src/controllers/account.ts
src/controllers/nino.ts
src/lib/nationalInsurance.ts
src/locales/cy/translation.json
src/locales/en/translation.json
src/routes/account.ts
src/routes/nino.ts
src/views/account/access-management.njk

This PR adds in the access grant flow for the National Insurance number app. A user can now:
1. Start at `/nino` in the DWP app
2. Enter their NI number
3. Click to save their number
4. The DWP app generates an access request and redirects the user to a new page in the account management app
5. The account management app displays the access request and allows the user to allow or deny it
6. If they accept, they're redirected back to the DWP app with an access grant.
7. The DWP app uses this access grant to write the NI number to their pod
The content and design of some screens here is very much WIP. Follow up PRs can improve these, this one is just about getting the flow working.
We're not writing the binary VC to a user's pod like we were for the identity VCs. This is because the Inrupt …

GUA-311 - Access Grant Flow

---

src/public/stylesheets/application.scss
src/views/dbs/request-a-basic-dbs-check.njk
src/views/layouts/base.njk
src/views/layouts/govuk.njk
src/views/personal-tax/sign-in-or-set-up.njk

Make our fake "GOVUK" pages in the app look a bit more like GOVUK and a bit less like a service page through removal of the phase banner, addition of breadcrumbs and minor spacing tweaks.
Not adding the super nav to these pages right now as it would add a lot of CSS and JS to the payload for very little benefit, so hopefully the basic GOVUK nav will do.

BAU: make dbs/pta start pages look more like GOVUK

---

src/controllers/login.ts
src/routes/login.ts
src/views/index.njk

This is a bit of a hack because users of the PoC app are logged in to
two separate external services - DI's Auth and the ESS broker.
Both support OIDC standards compliant logout, but it'll be a bit
complicated to set up and we'd need to get someone on Auth or DfA to
add a logout redirect URL to the client registry for us.
Instead, simply add two buttons on the homepage which each log the
user out of one external service.

GUA-324: Add logout buttons to the homepage

---

docs/README.md

These flow charts are simplified versions of the screens a user would
see, with enough of the 'what's going on behind the scenes' added to
make them useful in explaining the prototype.
Between the screens in Figma, these diagrams and the sequence diagrams
that Max added, we should have information for any level of technical
interest.
---
[Rendered page](https://github.com/alphagov/di-solid-prototype/tree/GUA-250-diagrams/docs)

GUA-250: Add journey flowcharts

---

docs/README.md

I think this is correct, but it's possible I've misunderstood the diagram.
The fictional NINO checker service would be run
by DWP in real life. So it would be DWP writing
this data to the Pod.
By coincidence, this would also make the diagram easier to follow, as would become easier to distinguish the two services involved (PTA = HMRC; NINO checker = DWP)

Correct 'HMRC' to 'DWP' in stretch goal diagram
