alphagov/di-solid-prototype

infrastructure/common/template.yaml, infrastructure/fargate-demo/template.yaml, infrastructure/kubernetes-demo/README.md, infrastructure/kubernetes-demo/hello-world.yaml, infrastructure/kubernetes-demo/samconfig.toml, infrastructure/kubernetes-demo/template.yaml
Set up an EKS cluster using Fargate compute and define a Kubernetes app to run a Hello World container. 
This app is already running and is accessible at http://k8s-hellowor-hellowor-f47db68a2b-297413031.eu-west-2.elb.amazonaws.com.
This PR adds a CloudFormation template and SAM config to create the EKS cluster and all other resources and a `.yaml` file that defines all the Kubernetes objects, but there are further actions that need to be taken between creating the cluster and deploying the app to it. See the new list of instructions in `infrastructure/kubernetes-demo/README.md` for details.
It's probably easiest to review this PR by looking at each commit individually
---
[Trello](https://trello.com/c/OwsBCUsX/1341-deploy-a-hello-world-node-app-to-eks-with-a-backing-service)
=> Deploy a demo app to Kubernetes

.gitignore, infrastructure/kubernetes-demo/hello-node-eks/.dockerignore, infrastructure/kubernetes-demo/hello-node-eks/Dockerfile, infrastructure/kubernetes-demo/hello-node-eks/index.js, infrastructure/kubernetes-demo/hello-node-eks/package-lock.json, infrastructure/kubernetes-demo/hello-node-eks/package.json, infrastructure/kubernetes-demo/hello-world.yaml, infrastructure/kubernetes-demo/template.yaml
Set up a simple Hello World Node app that fetches a secret from AWS secrets manager and displays it to prove it's worked. 
A follow up PR will fetch the other database details from the environment variables added in [7b41839](https://github.com/alphagov/di-solid-prototype/pull/6/commits/7b4183958bf4293bea8d42675acff388a07bdd64) and read / write to the database.
---
[Trello](https://trello.com/c/COBq3ILM/1362-create-a-mongodb-backing-service-that-speaks-to-the-eks-cluster)
=> Fetch database credentials from Secrets Manager

infrastructure/ess/template.yaml
Woops our Kafka version was 2.2.1
=> Upgrade Kafka to 2.8.1

README.md, nodemon.json, package-lock.json, package.json
Add nodemon to refresh the app as changes happen to source files.
=> Add nodemon to improve dev experience

.github/workflows/build_and_deploy.yaml, .github/workflows/cloudformation-lint.yaml, infrastructure/prototype-app/template.yaml
Use [aws-actions/amazon-ecr-login](https://github.com/marketplace/actions/amazon-ecr-login-action-for-github-actions) and a newly created Github Specific OIDC ARN to try and log in, then build our world in docker, push to ECR and Sam Deploy
=> GUA-220 Build, Push and SAM deploy with Github Actions

.github/workflows/build_and_deploy.yaml, infrastructure/prototype-app/template.yaml
Further Tweaks and fixes to CI
=> Gua 220 fixes to ci

.github/workflows/build_and_deploy.yaml, infrastructure/prototype-app/template.yaml
=> Gua 220 further changes to ci

.github/workflows/build_and_deploy.yaml
Unsure about this parameter going to give this a go.
=> Make task definition a file path

src/controllers/login.ts
=> Use the GDS ESS broker

src/controllers/identity/save.ts, src/views/login/start.njk
Tiny changes to update the Welcome message (on the Login page), and also to redirect to the correct template page if you save you identity.
=> Update welcome message, redirect to correct SAVED template

src/app.ts, src/controllers/dbs.ts, src/locales/cy/translation.json, src/locales/en/translation.json, src/routes/dbs.ts, src/views/dbs/apply-for-a-basic-dbs-check.njk, src/views/dbs/certificate-address-where.njk, src/views/dbs/check-your-details.njk, src/views/dbs/disclaimer.njk, src/views/dbs/driving-licence.njk, src/views/dbs/email-address.njk, src/views/dbs/layout.njk, src/views/dbs/mobile-number.njk, src/views/dbs/nino.njk, src/views/dbs/other-names.njk, src/views/dbs/prove-your-identity.njk, src/views/dbs/request-a-basic-dbs-check.njk, src/views/dbs/review-your-application.njk, src/views/dbs/what-is-your-sex.njk, src/views/dbs/where-were-you-born.njk, src/views/dbs/who-paying.njk, src/views/index.njk, src/views/layouts/base.njk, src/views/layouts/service.njk
This contains templates for the mock user journey for the DBS check service.
These are just static pages for now, they do not do anything, it's just a whole lot of layout and content.
=> GUA-212: Add templates, views and content for DBS

src/controllers/personalTax.ts, src/routes/personalTax.ts, src/views/index.njk
Wires up the personal tax account journey.
Not entirely clear on the order from [the Figma ](https://www.figma.com/file/f6Kn3ZhjCiiJSIQpNFt7On/Solid-example-flows?node-id=1432%3A2155).
But have assumed it's
Start -> Choose -> Home?
=> GUA-231: Wire up Personal Tax Account

src/controllers/identity/complete.ts
=> BAU: Fix stupid error introduced as merge conflict

src/controllers/personalTax.ts, src/routes/personalTax.ts
Extension of the last PR, after realising the PTA stuff needed to query solid for ID checks like DBS and wasn't just a Demo Potemkin Application
=> GUA-231 - Put personal Tax account behind Auth and Identity checks

src/controllers/account.ts, src/controllers/identity/save.ts, src/lib/pod.ts
Can get poor pat out of the path name now :)
=> BAU: Rename paths VCs are stored at

src/controllers/account.ts, src/lib/credentials.ts, src/lib/kvbCheckVc.ts, src/lib/passportCheckVc.ts, src/lib/pod.ts, src/views/account/your-proof-of-identity.njk
Write a localised description and createdAt timestamp when we PUT the VC.
Then read it back out and render it in the app
=> GUA-302: Write localised Description + CreatedAt to VCs and read + render in Accounts

package.json, src/public/javascripts/application.js, src/public/stylesheets/application.scss, src/views/layouts/base.njk, src/views/personal-tax/home.njk
The secondary menu on the personal tax account home was not working
correctly. This includes and initialises the header module from GOVUK
Frontend as well as adding some CSS to ensure the nav works as intended.
https://user-images.githubusercontent.com/7116819/183714920-964b1bcb-0f28-44e4-9ab7-d78914fcd521.mov
=> Make secondary nav toggle work on mobile

infrastructure/ess-load-testing/README.md, infrastructure/ess-load-testing/samconfig.toml, infrastructure/ess-load-testing/template.yaml
We'll need an S3 bucket, and appropriate permissions to output the
reports. Also the ability to run the load testing containers with a
fargate profile within the cluster
=> GUA-296: Defined new AWS services for Load Testing

src/views/dbs/review-your-application.njk
Otherwise submitting the form takes you to https://prototype.solid.integration.account.gov.uk/review-your-application which is a 404.
=> GUA-324: Fix broken link

src/locales/cy/translation.json, src/locales/en/translation.json
Here we introduce two commits that add a missing consonant to the language strings.
=> typos : you'l > you'll
